/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.praktikum8;

/**
 *
 * @author ASUS
 */
public class AplikasiSuhu extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiSuhu
     */
    public AplikasiSuhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaAplikasi = new javax.swing.JLabel();
        labelCelcius = new javax.swing.JLabel();
        inputCelcius = new javax.swing.JTextField();
        labelReamur = new javax.swing.JLabel();
        inputReamur = new javax.swing.JTextField();
        labelFahrenHeit = new javax.swing.JLabel();
        inputFahrenHeit = new javax.swing.JTextField();
        labelKelvin = new javax.swing.JLabel();
        inputKelvin = new javax.swing.JTextField();
        tombolKonversi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        namaAplikasi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        namaAplikasi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaAplikasi.setText("Aplikasi Suhu");

        labelCelcius.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelCelcius.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCelcius.setText("Celcius");

        inputCelcius.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        labelReamur.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelReamur.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelReamur.setText("Reamur");

        inputReamur.setEditable(false);
        inputReamur.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        labelFahrenHeit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelFahrenHeit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelFahrenHeit.setText("FahrenHeit");

        inputFahrenHeit.setEditable(false);
        inputFahrenHeit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        labelKelvin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelKelvin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelKelvin.setText("Kelvin");

        inputKelvin.setEditable(false);
        inputKelvin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tombolKonversi.setText("Konversi");
        tombolKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolKonversiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tombolKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(namaAplikasi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelReamur, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelKelvin, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFahrenHeit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputKelvin, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(inputFahrenHeit)
                            .addComponent(inputReamur)
                            .addComponent(inputCelcius))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(namaAplikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelCelcius, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputCelcius, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelReamur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputReamur, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelFahrenHeit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputFahrenHeit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelKelvin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputKelvin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(tombolKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolKonversiActionPerformed
        // TODO add your handling code here:
        String strCelcius = inputCelcius.getText();
        
        try{
            Double.parseDouble(strCelcius);
        } catch (Exception e) {
            return;
        }
        
        double celcius = Double.parseDouble(strCelcius);
        double reamur = (4 * celcius) / 5;
        double fahrenHeit = (9 / 5 * celcius) + 32;
        double kelvin = celcius + 273;
        
        String strReamur = Double.toString(reamur);
        String strFahrenHeit = Double.toString(fahrenHeit);
        String strKelvin = Double.toString(kelvin);
  
        inputReamur.setText(strReamur);
        inputFahrenHeit.setText(strFahrenHeit);
        inputKelvin.setText(strKelvin);
    }//GEN-LAST:event_tombolKonversiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputCelcius;
    private javax.swing.JTextField inputFahrenHeit;
    private javax.swing.JTextField inputKelvin;
    private javax.swing.JTextField inputReamur;
    private javax.swing.JLabel labelCelcius;
    private javax.swing.JLabel labelFahrenHeit;
    private javax.swing.JLabel labelKelvin;
    private javax.swing.JLabel labelReamur;
    private javax.swing.JLabel namaAplikasi;
    private javax.swing.JButton tombolKonversi;
    // End of variables declaration//GEN-END:variables
}
