/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.praktikum9;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class EditDataPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditDataPanel
     */
    public EditDataPanel() {
        initComponents();
        disableEditing();
    }
    
    private void disableEditing(){
        inputNama.setEditable(false);
        inputProdi.setEnabled(false);
        inputEditNim.setEditable(false);
        tombolLakiLaki.setEnabled(false);
        tombolPerempuann.setEnabled(false);
        checkBoxStatus.setEnabled(false);
        tombolUbah.setEnabled(false);
        tombolHapus.setEnabled(false);
    }
    
    private void enableEditing(){
        inputNama.setEditable(true);
        inputProdi.setEnabled(true);
        inputEditNim.setEditable(true);
        tombolLakiLaki.setEnabled(true);
        tombolPerempuann.setEnabled(true);
        checkBoxStatus.setEnabled(true);
        tombolUbah.setEnabled(true);
        tombolHapus.setEnabled(true);
    }

    private void clearForm(){
        inputNama.setText("");
        inputNim.setText("");
        inputProdi.setSelectedIndex(-1);
        inputEditNim.setText("");
        jenisKelaminButtonGroup.clearSelection();
        checkBoxStatus.setSelected(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisKelaminButtonGroup = new javax.swing.ButtonGroup();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        inputNim = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputProdi = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tombolLakiLaki = new javax.swing.JRadioButton();
        tombolPerempuann = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        checkBoxStatus = new javax.swing.JCheckBox();
        tombolUbah = new javax.swing.JButton();
        tombolHapus = new javax.swing.JButton();
        tombolCekData = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        inputEditNim = new javax.swing.JTextField();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("NIM");

        inputNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNimActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Cek Data");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Prodi");

        inputProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S1 Teknik Informatika", "S1 Teknik Elektro", "D3 Teknik Elektro" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Jenis Kelamin");

        jenisKelaminButtonGroup.add(tombolLakiLaki);
        tombolLakiLaki.setText("Laki-Laki");
        tombolLakiLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolLakiLakiActionPerformed(evt);
            }
        });

        jenisKelaminButtonGroup.add(tombolPerempuann);
        tombolPerempuann.setText("Perempuan");
        tombolPerempuann.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolPerempuannActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Status");

        checkBoxStatus.setText("Aktif");

        tombolUbah.setText("Ubah");
        tombolUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolUbahActionPerformed(evt);
            }
        });

        tombolHapus.setText("Hapus");
        tombolHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHapusActionPerformed(evt);
            }
        });

        tombolCekData.setText("Cek Data");
        tombolCekData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolCekDataActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Ubah Data");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("NIM");

        inputEditNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEditNimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inputNim, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tombolCekData)))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkBoxStatus)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tombolLakiLaki)
                                        .addGap(36, 36, 36)
                                        .addComponent(tombolPerempuann))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tombolUbah)
                                        .addGap(18, 18, 18)
                                        .addComponent(tombolHapus))))
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputEditNim, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(30, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tombolCekData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputEditNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tombolLakiLaki)
                    .addComponent(tombolPerempuann))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(checkBoxStatus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolUbah)
                    .addComponent(tombolHapus))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tombolLakiLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolLakiLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tombolLakiLakiActionPerformed

    private void tombolPerempuannActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolPerempuannActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tombolPerempuannActionPerformed

    private void tombolCekDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolCekDataActionPerformed
        String nim = inputNim.getText();
        boolean ditemukan = false;
        try {
            Long.parseLong(nim);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Silakan masukkan NIM berupa angka");
            return;
        }

        for (Mahasiswa m : Mahasiswa.mahasiswas) {
            if (m.getNim().equals(nim)) {
                inputNama.setText(m.getNama());
                inputProdi.setSelectedItem(m.getProdi());
                inputEditNim.setText(m.getNim());
                if (m.getJenisKelamin().equals("Laki - Laki")) {
                    tombolLakiLaki.setSelected(true);
                } else {
                    tombolPerempuann.setSelected(true);
                }
                checkBoxStatus.setSelected(m.isIsActive());
                ditemukan = true;
                enableEditing();
                break;
            }
        }
        if(!ditemukan){
            JOptionPane.showMessageDialog(this, "Data tidak ditemukan");
        }
    }//GEN-LAST:event_tombolCekDataActionPerformed

    private void inputEditNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEditNimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEditNimActionPerformed

    private void tombolUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolUbahActionPerformed
        // TODO add your handling code here:
        String nim = inputNim.getText(); // ambil NIM yang diubah
        String editNim = inputEditNim.getText();
        String nama = inputNama.getText();
        String prodi = inputProdi.getSelectedItem().toString();
        String jenisKelamin = tombolLakiLaki.isSelected() ? "Laki - Laki" : "Perempuan";
        boolean aktif = checkBoxStatus.isSelected();

        try {
            Long.parseLong(editNim);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Silakan masukkan NIM baru berupa angka");
            return;
        }
        
        boolean ditemukan = false;
        for (Mahasiswa m : Mahasiswa.mahasiswas) {
            if (m.getNim().equals(nim)) {
                for (Mahasiswa i : Mahasiswa.mahasiswas) {
                    if(i.getNim().equals(editNim) && !(nim.equals(editNim))){
                        JOptionPane.showMessageDialog(this, "NIM baru sudah ada sebelumnya, silakan masukkan NIM lain");
                        return;
                    }
                }
                m.setNama(nama);
                m.setNim(editNim);
                m.setProdi(prodi);
                m.setJenisKelamin(jenisKelamin);
                m.setIsActive(aktif);
                JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
                ditemukan = true;
                break;
            }
        }

        if (!ditemukan) {
            JOptionPane.showMessageDialog(this, "Data dengan NIM " + nim + " tidak ditemukan!");
        }
        clearForm();
        disableEditing();
    }//GEN-LAST:event_tombolUbahActionPerformed

    private void tombolHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHapusActionPerformed
        // TODO add your handling code here:
        String nim = inputNim.getText(); // ambil NIM dari field input
        Mahasiswa target = null;

        for (Mahasiswa m : Mahasiswa.mahasiswas) {
            if (m.getNim().equals(nim)) {
                target = m;
                break;
            }
        }

        if (target != null) {
            int konfirmasi = JOptionPane.showConfirmDialog(this, 
                "Yakin ingin menghapus data dengan NIM " + nim + "?", 
                "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

            if (konfirmasi == JOptionPane.YES_OPTION) {
                Mahasiswa.mahasiswas.remove(target);
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                // Kosongkan form setelah hapus
                inputNama.setText("");
                inputNim.setText("");
                inputProdi.setSelectedIndex(0);
                jenisKelaminButtonGroup.clearSelection();
                checkBoxStatus.setSelected(false);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Data tidak ditemukan!");
        }
        clearForm();
        disableEditing();
    }//GEN-LAST:event_tombolHapusActionPerformed

    private void inputNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNimActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBoxStatus;
    private javax.swing.JTextField inputEditNim;
    private javax.swing.JTextField inputNama;
    private javax.swing.JTextField inputNim;
    private javax.swing.JComboBox<String> inputProdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.ButtonGroup jenisKelaminButtonGroup;
    private javax.swing.JButton tombolCekData;
    private javax.swing.JButton tombolHapus;
    private javax.swing.JRadioButton tombolLakiLaki;
    private javax.swing.JRadioButton tombolPerempuann;
    private javax.swing.JButton tombolUbah;
    // End of variables declaration//GEN-END:variables
}
