/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.praktikum9;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class TambahDataPanel extends javax.swing.JPanel {

    /**
     * Creates new form TambahDataPanel
     */
    public TambahDataPanel() {
        initComponents();
    }

    private void clearForm(){
        namaTextField.setText("");
        nimTextField.setText("");
        jenisKelaminButtonGroup.clearSelection();
        aktifCheckBox.setSelected(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisKelaminButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelTambahDataMahasiswa = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        namaTextField = new javax.swing.JTextField();
        nimTextField = new javax.swing.JTextField();
        labelNIM = new javax.swing.JLabel();
        labelProdi = new javax.swing.JLabel();
        prodiComboBox = new javax.swing.JComboBox<>();
        labelJenisKelamin = new javax.swing.JLabel();
        lakiLakiRadioButton = new javax.swing.JRadioButton();
        perempuanRadioButton = new javax.swing.JRadioButton();
        labelStatus = new javax.swing.JLabel();
        aktifCheckBox = new javax.swing.JCheckBox();
        tombolKirim = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelTambahDataMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTambahDataMahasiswa.setText("Tambah Data Mahasiswa");

        labelNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNama.setText("Nama");

        namaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextFieldActionPerformed(evt);
            }
        });

        nimTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimTextFieldActionPerformed(evt);
            }
        });

        labelNIM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNIM.setText("NIM");

        labelProdi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelProdi.setText("Prodi");

        prodiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S1 Teknik Informatika", "S1 Teknik Elektro", "D3 Teknik Elektro" }));
        prodiComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodiComboBoxActionPerformed(evt);
            }
        });

        labelJenisKelamin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelJenisKelamin.setText("Jenis Kelamin");

        lakiLakiRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        jenisKelaminButtonGroup.add(lakiLakiRadioButton);
        lakiLakiRadioButton.setText("Laki Laki");
        lakiLakiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiLakiRadioButtonActionPerformed(evt);
            }
        });

        perempuanRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        jenisKelaminButtonGroup.add(perempuanRadioButton);
        perempuanRadioButton.setText("Perempuan");

        labelStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelStatus.setText("Status");

        aktifCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        aktifCheckBox.setText("Aktif");
        aktifCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aktifCheckBoxActionPerformed(evt);
            }
        });

        tombolKirim.setBackground(new java.awt.Color(51, 255, 255));
        tombolKirim.setText("Kirim");
        tombolKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolKirimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTambahDataMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelProdi)
                                .addComponent(labelNIM))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(perempuanRadioButton)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelNama)
                                .addComponent(labelJenisKelamin)
                                .addComponent(labelStatus))
                            .addGap(22, 22, 22)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(prodiComboBox, 0, 390, Short.MAX_VALUE)
                                .addComponent(nimTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                                .addComponent(aktifCheckBox)
                                .addComponent(lakiLakiRadioButton)
                                .addComponent(tombolKirim)
                                .addComponent(namaTextField))
                            .addContainerGap(16, Short.MAX_VALUE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTambahDataMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNama)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNIM)
                    .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelProdi))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJenisKelamin)
                    .addComponent(lakiLakiRadioButton)
                    .addComponent(perempuanRadioButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStatus)
                    .addComponent(aktifCheckBox))
                .addGap(18, 18, 18)
                .addComponent(tombolKirim, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents
    
    private void namaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTextFieldActionPerformed

    private void nimTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimTextFieldActionPerformed

    private void lakiLakiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiLakiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiLakiRadioButtonActionPerformed

    private void aktifCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aktifCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aktifCheckBoxActionPerformed

    private void prodiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodiComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodiComboBoxActionPerformed

    private void tombolKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolKirimActionPerformed
        // TODO add your handling code here:
        String nama = namaTextField.getText();
        String nim = nimTextField.getText();
        String prodi = (String) prodiComboBox.getSelectedItem();
        String jenisKelamin = lakiLakiRadioButton.isSelected() ? "Laki - Laki" : "Perempuan";
        boolean isActive = aktifCheckBox.isSelected();
        
        if (nama.equals("") || nim.equals("") || !(lakiLakiRadioButton.isSelected() || perempuanRadioButton.isSelected())) {
            JOptionPane.showMessageDialog(this, "Silakan lengkapi data anda");
            return;
        }
        
        try {
            Long.parseLong(nim);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Silakan masukkan NIM berupa angka");
            return;
        }
        
        Mahasiswa mahasiswa = new Mahasiswa(nama, nim, prodi, jenisKelamin, isActive);
        for (Mahasiswa m : Mahasiswa.mahasiswas) {
            if (m.getNim().equals(nim)) {
                JOptionPane.showMessageDialog(this, "Data mahasiswa sudah ada sebelumnya");
                return;
            }
        }
        Mahasiswa.mahasiswas.add(mahasiswa);
       
        JOptionPane.showMessageDialog(this, "Sukses menambahkan data " + nama);
        clearForm();
    }//GEN-LAST:event_tombolKirimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aktifCheckBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup jenisKelaminButtonGroup;
    private javax.swing.JLabel labelJenisKelamin;
    private javax.swing.JLabel labelNIM;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelProdi;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelTambahDataMahasiswa;
    private javax.swing.JRadioButton lakiLakiRadioButton;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JComboBox<String> prodiComboBox;
    private javax.swing.JButton tombolKirim;
    // End of variables declaration//GEN-END:variables
}
